# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5fa0076d1ea31df18480d8cf7e9fae577aa358af10502503c0775b956b7fa8e7b588fea7ef5ff47d9b296f5383b34981ed3d7c028b20ab39d10d001c06f6d45

test:
  secret_key_base: bfb32607b75d2fdc4f114a28edca393d5961efca40c9990afad8740e8b1ff487f098fe01b666ea9a6a2c3cae0b3576077105e37ef89ee795cc2e66e4f71b00c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
